E-Ticaret/OnlineTicariOtomasyon/OnlineTicariOtomasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace OnlineTicariOtomasyon.Controllers
{
    public class CariController : Controller
    {
        // GET: Cari
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Carilers.Where(x => x.Durum== true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult CariEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CariEkle(Cariler k)
        {
            c.Carilers.Add(k);//d den gelen değeri ekle
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var cari = c.Carilers.Find(id);//dışarıdan gönderilen id yi bul
            cari.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CariGetir(int id)
        {
            var cari = c.Carilers.Find(id);
            return View("CariGetir",cari);
        }
        public ActionResult CariGuncelle(Cariler d)
        {
            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var cr = c.Carilers.Find(d.CariID);
            cr.CariAd = d.CariAd;
            cr.CariSoyad = d.CariSoyad;
            cr.CariSehir = d.CariSehir;
            cr.CariMail = d.CariMail;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSatis(int id)
        {
            var degerler = c.SatisHarakets.Where(x => x.Cariid == id).ToList();
            var dpt = c.Carilers.Where(x => x.CariID == id).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.dp = dpt;
            return View(degerler);
        }
    }
}

E-Ticaret/OnlineTicariOtomasyon/OnlineTicariOtomasyon/Views/Cari/CariEkle.cshtml
@model  MvcOnlineTicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>CariEkle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
    @Html.HiddenFor(x=>x.CariID)
    <button class="btn btn-primary">KAYDET</button>
</form>

E-Ticaret/OnlineTicariOtomasyon/OnlineTicariOtomasyon/Views/Cari/CariGetir.cshtml
@model  MvcOnlineTicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Cari Güncelleme Ekranı</h2>
<br />
@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:orange" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
    @Html.HiddenFor(x => x.CariID)
</div>
    <button class="btn btn-warning">Güncelle</button>
}

E-Ticaret/OnlineTicariOtomasyon/OnlineTicariOtomasyon/Views/Cari/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Cariler</h2>
<br />
<table class="table table-striped" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>ADI</th>
        <th>SOYADI</th>
        <th>ŞEHİR</th>
        <th>MAİL</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>DETAYLAR</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.CariID</td>
            <td>@k.CariAd</td>
            <td>@k.CariSoyad</td>
            <td>@k.CariSehir</td>
            <td>@k.CariMail</td>
            <td><a href="/Cari/CariSil/@k.CariID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@k.CariID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Cari/MusteriSatis/@k.CariID" class="btn btn-info">Satış Geçmişi</a></td>
        </tr>
    }
</table>
<a href="/Cari/CariEkle" class="btn btn-info">Yeni Cari Ekle</a>

E-Ticaret/OnlineTicariOtomasyon/OnlineTicariOtomasyon/Views/Cari/MusteriSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHaraket>
@{
    ViewBag.Title = "MusteriSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Müşteri Satis</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active" style="color:black; font-size:20px;">
        Cari Adı : @ViewBag.dp
    </li>
</ol>
<table class="table table-hover">
    <tr>
        <th>SATIŞ ID</th>
        <th>PERSONEL</th>
        <th>URUN</th>
        <th>ADET</th>
        <th>FİYAT</th>
        <th>TOPLAM TUTAR</th>
        <th>TARİH</th>
        <th>YAZDIR</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.SatisID</td>
            <td>@k.Personel.PersonelAd @k.Personel.PersonelSoyad</td>
            <td>@k.Urun.UrunAd</td>
            <td>@k.Adet</td>
            <td>@k.Fiyat</td>
            <td>@k.ToplamTutar</td>
            <td>@k.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:chartreuse; color:white;">Yazdır</a></td>
        </tr>
    }

</table>